name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download modules
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: Check formatting
        run: |
          fmtout=$(gofmt -s -l .)
          if [ -n "$fmtout" ]; then
            echo "Files not formatted:" >&2
            echo "$fmtout" >&2
            exit 1
          fi

      - name: Run tests (no race detector)
        run: go test ./... -v
