name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download modules
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: Format and check
        run: |
          # Format all Go files
          gofmt -s -w .
          
          # Check if there are any uncommitted changes
          if ! git diff --quiet; then
            echo "Code formatting issues found. The following files need formatting:"
            git diff --name-only
            echo ""
            echo "Please run 'gofmt -s -w .' locally and commit the changes."
            exit 1
          fi

      - name: Run tests (no race detector)
        run: go test ./... -v
